//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimyWebServies
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClaimyWebServies_dbEntities2 : DbContext
    {
        public ClaimyWebServies_dbEntities2()
            : base("name=ClaimyWebServies_dbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ClaimHistory> tbl_ClaimHistory { get; set; }
        public virtual DbSet<tbl_Claims> tbl_Claims { get; set; }
        public virtual DbSet<tbl_Countries> tbl_Countries { get; set; }
        public virtual DbSet<tbl_Images> tbl_Images { get; set; }
        public virtual DbSet<tbl_LoginType> tbl_LoginType { get; set; }
        public virtual DbSet<tbl_ParkingCompanies> tbl_ParkingCompanies { get; set; }
        public virtual DbSet<tbl_ParkingReasons> tbl_ParkingReasons { get; set; }
        public virtual DbSet<tbl_Status> tbl_Status { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tbl_ZipCodes> tbl_ZipCodes { get; set; }
    }
}
