//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimyWebServies
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Countries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Countries()
        {
            this.tbl_Claims = new HashSet<tbl_Claims>();
            this.tbl_ParkingReasons = new HashSet<tbl_ParkingReasons>();
            this.tbl_ParkingCompanies = new HashSet<tbl_ParkingCompanies>();
            this.tbl_ZipCodes = new HashSet<tbl_ZipCodes>();
        }
    
        public int fld_CountryID { get; set; }
        public string fld_Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Claims> tbl_Claims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ParkingReasons> tbl_ParkingReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ParkingCompanies> tbl_ParkingCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZipCodes> tbl_ZipCodes { get; set; }
    }
}
