//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimyWebServies
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ClaimHistory
    {
        public int fld_HistoryId { get; set; }
        public int fld_ClaimID { get; set; }
        public System.DateTime fld_ActionTimeDate { get; set; }
        public int fld_UserID { get; set; }
        public int fld_StatusID { get; set; }
        public string fld_ClaimHistoryMessage { get; set; }
    
        public virtual tbl_Claims tbl_Claims { get; set; }
        public virtual tbl_Status tbl_Status { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
