//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimyWebServies
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Claims
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Claims()
        {
            this.tbl_ClaimHistory = new HashSet<tbl_ClaimHistory>();
            this.tbl_Images = new HashSet<tbl_Images>();
        }
    
        public int fld_ClaimID { get; set; }
        public System.DateTime fld_ClaimTimeDate { get; set; }
        public int fld_UserID { get; set; }
        public int fld_CountryID { get; set; }
        public int fld_ParkingCompanyID { get; set; }
        public int fld_ReasonID { get; set; }
        public string fld_TicketNo { get; set; }
        public System.DateTime fld_TicketTimeDate { get; set; }
        public System.DateTime fld_TicketDueDate { get; set; }
        public int fld_TicketFee { get; set; }
        public string fld_TicketStreetName { get; set; }
        public int fld_ZipCode { get; set; }
        public string fld_CarRegNo { get; set; }
        public string fld_CarBrand { get; set; }
        public string fld_CarModel { get; set; }
        public string fld_ClaimComments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ClaimHistory> tbl_ClaimHistory { get; set; }
        public virtual tbl_Countries tbl_Countries { get; set; }
        public virtual tbl_ParkingCompanies tbl_ParkingCompanies { get; set; }
        public virtual tbl_ParkingReasons tbl_ParkingReasons { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_ZipCodes tbl_ZipCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Images> tbl_Images { get; set; }
    }
}
