//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimyWebServies
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ParkingCompanies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ParkingCompanies()
        {
            this.tbl_Claims = new HashSet<tbl_Claims>();
        }
    
        public int fld_ParkingCompanyID { get; set; }
        public int fld_CountryID { get; set; }
        public string fld_CompanyCVR { get; set; }
        public string fld_CompanyName { get; set; }
        public string fld_CompanyStreet { get; set; }
        public int fld_ZipCode { get; set; }
        public string fld_CompanyEmail { get; set; }
        public string fld_CompanyPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Claims> tbl_Claims { get; set; }
        public virtual tbl_Countries tbl_Countries { get; set; }
        public virtual tbl_ZipCodes tbl_ZipCodes { get; set; }
    }
}
